name: Vulnerable Functionality test

on: [push]

jobs:
  vulnfunc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: TeodorBucht1729/vulnerable-functionality/javascript@master
      with:
        root-packagejson-directory: 'javascript/test/import_from_inside'

